### PR TITLE
Fix inspektor LinterStats no attribute get issue

### PR DESCRIPTION
**Pull request by chunfuwen**
Linterstats should be a list

Signed-off-by: chunfuwen <chwen@redhat.com>

### CODE REVIEW

**Comment by chunfuwen** [comment]
Issue log:https://github.com/autotest/tp-libvirt/runs/4330091467?check_suite_focus=true
******************************
Run inspekt checkall --disable-style E501,E265,W601,W605,E402,E722,E741 --no-license-check
  inspekt checkall --disable-style E501,E265,W601,W605,E402,E722,E741 --no-license-check
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.6.15/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.6.15/x64/lib
PEP8 disabled: E501,E265,W601,W605,E402,E722,E741
Pylint disabled: W,R,C,E1002,E1101,E1103,E1120,F0401,I0011
Pylint enabled : W0611
License check: disabled
'LinterStats' object has no attribute 'get'
Error: Process completed with exit code 1.
*****************************************************

**Comment by chunfuwen** [comment]
After change, and test local environment , the issue is fixed:

(testinspec) [root@hp-dl360g9-16 tp-libvirt]# inspekt checkall --disable-style E501,E265,W601,W605,E402,E722,E741 --no-license-check
PEP8 disabled: E501,E265,W601,W605,E402,E722,E741
Pylint disabled: W,R,C,E1002,E1101,E1103,E1120,F0401,I0011
Pylint enabled : W0611
License check: disabled
Global check PASS

**Review by kamilvarga — APPROVED** [review]
LGTM.

**Comment by iccaszhulili** [comment]
LGTM

**Comment by chunfuwen** [comment]
@clebergnu could you please take a look since it is urgent? thanks.

**Comment by Yingshun** [comment]
@chunfuwen   It works in my environment with pylint 2.11.1, so it might be a pylint issue I think... Please see(https://github.com/autotest/tp-libvirt/pull/3894)

**Comment by DanielNoord** [comment]
Contributor to `pylint` here.
Sorry about this bug. We did not consider this part of our API to be public.

While removing this particular piece of code makes the code backwards compatible, an actual fix for this bug which retains the previous functionality would be:
```python
           for module, status in runner.linter.stats.by_module.items():
                 if any(status.values()):
                     self.log.debug('Lint: %s FAIL', module)
                 else:
                     self.log.debug('Lint: %s PASS', module)
```

However, this would require to update the dependency on `pylint` to `2.12+`.
If this is indeed desired @chunfuwen would need to update the PR as I can't make a suggestion on removed code.

**Review by ldoktor — CHANGES_REQUESTED** [review]
Hello @chunfuwen, this would remove the list of pass/fail lints, which is quite useful. How about this backward-compatible version:

```diff
diff --git a/inspektor/lint.py b/inspektor/lint.py
index 41e1890..27a77fa 100644
--- a/inspektor/lint.py
+++ b/inspektor/lint.py
@@ -122,7 +122,12 @@ class Linter(object):
         linter_failed = True
         if paths:
             runner = QuietLintRun(self.get_opts() + paths, exit=False)
-            for module, status in runner.linter.stats.get('by_module').items():
+            if hasattr(runner.linter.stats, 'get'):
+                items = runner.linter.stats.get('by_module').items()
+            else:
+                items = runner.linter.stats.by_module.items()
+            for module, status in items:
+                status.pop("statement")
                 if any(status.values()):
                     self.log.debug('Lint: %s FAIL', module)
                 else:
```

I had to add the `status.pop("statement")` as the newer pylint reports them, which is not an error nor issue.

**Comment by clebergnu** [comment]
Hi @chunfuwen, looks like @ldoktor suggestion combines the best of both worlds.  Please consider that suggestion.  Thanks.

**Comment by chunfuwen** [comment]
@clebergnu 
@ldoktor 
Codes are updated accordingly as per above mentioned comments

**Review by ldoktor — APPROVED** [review]
Thank you, tested with stock (older) pylint as well as the latest from pip and seems to work well.

**Comment by chunfuwen** [comment]
@ldoktor 
Thank you for merging this PR.
Do you have plan to sync up with 
https://pypi.org/project/inspektor/ and release new tag: 0.5.3?
